import os
import subprocess
import tkinter as tk
from tkinter import messagebox, ttk
from tkinterdnd2 import DND_FILES, TkinterDnD
from datetime import datetime

class ToolTip:
    """Custom tooltip for widgets"""
    def __init__(self, widget, text):
        self.widget = widget
        self.text = text
        self.tooltip_window = None
        # Bind mouse enter and leave events to show/hide the tooltip
        widget.bind("<Enter>", self.show)
        widget.bind("<Leave>", self.hide)
    
    def show(self, event=None):
        """Display the tooltip near the widget"""
        if self.tooltip_window:
            return
        x = self.widget.winfo_rootx() + 25
        y = self.widget.winfo_rooty() + 25
        self.tooltip_window = tw = tk.Toplevel(self.widget)
        tw.wm_overrideredirect(True)  # Remove window decorations
        tw.wm_geometry(f"+{x}+{y}")
        label = tk.Label(
            tw, text=self.text, justify=tk.LEFT,
            background="#E8F4F8", foreground="#2C5F7A",
            relief=tk.SOLID, borderwidth=1,
            font=("Segoe UI", 9), padx=8, pady=6
        )
        label.pack()
    
    def hide(self, event=None):
        """Hide the tooltip"""
        if self.tooltip_window:
            self.tooltip_window.destroy()
            self.tooltip_window = None

def get_git_config(key):
    """Read a value from the global Git config"""
    try:
        result = subprocess.run(
            ["git", "config", "--global", key],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError:
        return ""

def convert_patch(input_path, output_path, user_name, user_email, commit_subject):
    """Convert a TortoiseSVN patch to a Git-compatible patch for 'git am'"""
    if not user_name.strip() or not user_email.strip():
        raise ValueError("User name and email are required to create the patch.")
    
    if not commit_subject.strip():
        raise ValueError("Commit message cannot be empty.")
    
    with open(input_path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()
    
    new_lines = []
    for line in lines:
        line = line.rstrip("\n\r")
        
        if line.startswith("Index: "):
            path = line.split("Index: ", 1)[1].strip()
            new_lines.append(f"diff --git a/{path} b/{path}")
            new_lines.append("index 0000000..1111111 100644")
        elif line.startswith("diff --git"):
            new_lines.append(line)
            new_lines.append("index 0000000..1111111 100644")
        elif line.startswith("---") and not line.startswith("--- a/"):
            path = line.split("--- ", 1)[1].split("\t")[0].strip()
            new_lines.append(f"--- a/{path}")
        elif line.startswith("+++") and not line.startswith("+++ b/"):
            path = line.split("+++ ", 1)[1].split("\t")[0].strip()
            new_lines.append(f"+++ b/{path}")
        elif line.startswith("===") or line.strip() == "---":
            continue  # skip separator lines
        else:
            new_lines.append(line)
    
    # Email-style header for git am with a custom Subject
    header = (
        "From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001\n"
        f"From: {user_name} <{user_email}>\n"
        f"Date: {datetime.now().strftime('%a, %d %b %Y %H:%M:%S %z')}\n"
        f"Subject: [PATCH] {commit_subject}\n"
        "\n"
    )
    
    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write("\n".join(new_lines))
        f.write("\n")

class PatchConverterApp:
    """Main application class for SVN → Git patch conversion"""
    def __init__(self, root):
        self.root = root
        self.root.title("SVN → Git Patch Converter")
        self.root.geometry("550x500")
        self.root.configure(bg="#F0F4F8")
        
        self.patch_file = None  # Currently loaded patch file
        
        # Top frame for drop area
        drop_frame = tk.Frame(root, bg="#D4E6F1", relief=tk.RIDGE, bd=2)
        drop_frame.pack(padx=20, pady=20, fill=tk.BOTH, expand=False)
        
        self.drop_label = tk.Label(
            drop_frame,
            text="📄 Drag your TortoiseSVN .patch file here",
            bg="#D4E6F1",
            fg="#2C5F7A",
            font=("Segoe UI", 12, "bold"),
            padx=20,
            pady=40
        )
        self.drop_label.pack()
        self.drop_label.drop_target_register(DND_FILES)
        self.drop_label.dnd_bind("<<Drop>>", self.handle_drop)
        
        ToolTip(self.drop_label, 
                "Drag your .patch file generated by TortoiseSVN here.\n"
                "The script will convert it to a Git-compatible format\n"
                "adding email-style headers and correct Git paths.")
        
        # Middle frame for configuration
        config_frame = tk.LabelFrame(
            root, text="⚙️ Patch Configuration", 
            bg="#E8F4F8", fg="#2C5F7A",
            font=("Segoe UI", 10, "bold"),
            padx=15, pady=10
        )
        config_frame.pack(padx=20, pady=10, fill=tk.BOTH, expand=True)
        
        # User name
        tk.Label(
            config_frame, text="Name:", 
            bg="#E8F4F8", fg="#34495E",
            font=("Segoe UI", 9)
        ).grid(row=0, column=0, sticky=tk.W, pady=5)
        
        self.name_var = tk.StringVar(value=get_git_config("user.name"))
        self.name_entry = tk.Entry(
            config_frame, textvariable=self.name_var,
            bg="#FFFFFF", fg="#2C3E50",
            font=("Segoe UI", 10),
            relief=tk.FLAT, bd=2
        )
        self.name_entry.grid(row=0, column=1, sticky=tk.EW, pady=5, padx=10)
        
        ToolTip(self.name_entry,
                "Full name of the patch author.\n"
                "Preloaded from: git config --global user.name\n"
                "You can modify it before conversion.")
        
        # Email
        tk.Label(
            config_frame, text="Email:", 
            bg="#E8F4F8", fg="#34495E",
            font=("Segoe UI", 9)
        ).grid(row=1, column=0, sticky=tk.W, pady=5)
        
        self.email_var = tk.StringVar(value=get_git_config("user.email"))
        self.email_entry = tk.Entry(
            config_frame, textvariable=self.email_var,
            bg="#FFFFFF", fg="#2C3E50",
            font=("Segoe UI", 10),
            relief=tk.FLAT, bd=2
        )
        self.email_entry.grid(row=1, column=1, sticky=tk.EW, pady=5, padx=10)
        
        ToolTip(self.email_entry,
                "Patch author's email.\n"
                "Preloaded from: git config --global user.email\n"
                "You can modify it before conversion.")
        
        # Commit message
        tk.Label(
            config_frame, text="Commit:", 
            bg="#E8F4F8", fg="#34495E",
            font=("Segoe UI", 9)
        ).grid(row=2, column=0, sticky=tk.W, pady=5)
        
        self.commit_var = tk.StringVar(value="Automatic SVN→Git conversion")
        self.commit_entry = tk.Entry(
            config_frame, textvariable=self.commit_var,
            bg="#FFFFFF", fg="#2C3E50",
            font=("Segoe UI", 10),
            relief=tk.FLAT, bd=2
        )
        self.commit_entry.grid(row=2, column=1, sticky=tk.EW, pady=5, padx=10)
        
        ToolTip(self.commit_entry,
                "Commit message (patch Subject line).\n"
                "Will appear in the header as 'Subject: [PATCH] <text>'\n"
                "Recommended: max 50 characters, imperative, no final period.\n"
                "Example: 'Fix adapter memory leak' or 'Add validation to SpecAdapter'")
        
        config_frame.columnconfigure(1, weight=1)
        
        # Bottom frame for convert button
        button_frame = tk.Frame(root, bg="#F0F4F8")
        button_frame.pack(padx=20, pady=10, fill=tk.X)
        
        self.convert_btn = tk.Button(
            button_frame,
            text="✅ Convert Patch",
            bg="#5DADE2",
            fg="#FFFFFF",
            font=("Segoe UI", 11, "bold"),
            relief=tk.FLAT,
            padx=20,
            pady=10,
            state=tk.DISABLED,
            cursor="hand2",
            command=self.convert_patch_action
        )
        self.convert_btn.pack()
        
        ToolTip(self.convert_btn,
                "Click to start patch conversion.\n"
                "The converted file will be saved in the same folder\n"
                "with '_git.patch' suffix and is compatible with:\n"
                "• git am --3way filename_git.patch\n"
                "• TortoiseGit → Apply Patch Serial")
        
        # Status label
        self.status_label = tk.Label(
            root, text="Waiting for patch file...",
            bg="#F0F4F8", fg="#7F8C8D",
            font=("Segoe UI", 9, "italic")
        )
        self.status_label.pack(pady=5)
    
    def handle_drop(self, event):
        """Handle a file dropped into the drop zone"""
        files = event.data.strip().strip('{}')
        
        if not os.path.isfile(files):
            messagebox.showwarning("Warning", "Please drop a single valid .patch file.")
            return
        
        if not files.lower().endswith(".patch"):
            messagebox.showwarning("Invalid format", "You must drop a .patch file.")
            return
        
        self.patch_file = files
        filename = os.path.basename(files)
        self.drop_label.config(text=f"✅ {filename}", bg="#ABEBC6")
        self.convert_btn.config(state=tk.NORMAL, bg="#27AE60")
        self.status_label.config(text=f"Loaded file: {filename}", fg="#27AE60")
    
    def convert_patch_action(self):
        """Execute patch conversion"""
        if not self.patch_file:
            messagebox.showwarning("Warning", "No file selected.")
            return
        
        user_name = self.name_var.get().strip()
        user_email = self.email_var.get().strip()
        commit_subject = self.commit_var.get().strip()
        
        if not user_name or not user_email:
            messagebox.showerror(
                "Missing data",
                "Name and email are required.\n\n"
                "Fill the fields or configure Git:\n"
                "git config --global user.name \"Your Name\"\n"
                "git config --global user.email \"you@example.com\""
            )
            return
        
        if not commit_subject:
            messagebox.showerror(
                "Missing commit message",
                "Commit message is required.\n\n"
                "Enter a short description (max 50 characters)."
            )
            return
        
        filename = os.path.basename(self.patch_file)
        if filename.lower().endswith(".patch"):
            filename = filename[:-6]
        
        output_path = os.path.join(
            os.path.dirname(self.patch_file), 
            filename + "_git.patch"
        )
        
        try:
            convert_patch(self.patch_file, output_path, user_name, user_email, commit_subject)
            messagebox.showinfo(
                "Conversion Completed",
                f"✅ Patch ready for git am:\n\n{output_path}\n\n"
                f"Use: git am --3way {os.path.basename(output_path)}"
            )
            self.status_label.config(
                text=f"Conversion completed: {os.path.basename(output_path)}", 
                fg="#27AE60"
            )
            # Reset UI
            self.patch_file = None
            self.drop_label.config(
                text="📄 Drag your TortoiseSVN .patch file here",
                bg="#D4E6F1"
            )
            self.convert_btn.config(state=tk.DISABLED, bg="#5DADE2")
        except ValueError as e:
            messagebox.showerror("Validation Error", str(e))
        except Exception as e:
            messagebox.showerror("Error", f"Error during conversion:\n{e}")

def main():
    """Launch the GUI application"""
    root = TkinterDnD.Tk()
    app = PatchConverterApp(root)
    root.mainloop()

if __name__ == "__main__":
    main()
